name: 📜 Script Issue Template
description: Template for script-related issues
title: "[ISSUE] [Type] - [Brief Description]"
labels: ["Script Issue"]
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "Type"
      description: "Select issue type"
      options:
        - "🐞 Bug Fix"
        - "✨ New Feature"
        - "🔄 Update"
        - "⚠️ Security"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "Title"
      description: "Concise issue title"
      placeholder: "Brief description of the issue"
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: "Problem Description"
      description: "Detailed explanation of the issue or feature request"
      placeholder: "Describe the problem, expected behavior, and actual behavior..."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Reproduction Steps"
      description: "Step-by-step instructions to reproduce the error"
      placeholder: |
        1. Action 1...
        2. Action 2...
        3. Action 3...
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: "Scope"
      description: "Where does this occur?"
      options:
        - "client"
        - "server"
        - "both"
    validations:
      required: true

  - type: checkboxes
    id: criticality
    attributes:
      label: "Impact/Criticality"
      description: "Select all that apply"
      options:
        - label: "Breaks existing functionality"
        - label: "Security vulnerability"
        - label: "Performance impact"
        - label: "Blocks development/workflow"
